"""Provider-neutral, local-first source-analysis contracts and runtime seams."""

from .aggregation import (
    AnalysisProgressRegressionError,
    ConfidenceAggregationError,
    aggregate_confidence,
    aggregate_progress,
)
from .models import (
    BASIS_POINTS,
    AnalysisCancellation,
    AnalysisCancellationReason,
    AnalysisEvidence,
    AnalysisExecutionMode,
    AnalysisFailure,
    AnalysisFailureCode,
    AnalysisMeasurement,
    AnalysisModel,
    AnalysisProgress,
    AnalysisRun,
    AnalysisRunId,
    AnalysisRunStatus,
    AnalysisStage,
    AnalysisStageKind,
    AnalysisStagePlan,
    AnalysisStageProgress,
    AnalysisStageStatus,
    ConfidenceAggregate,
    ConfidenceAssessment,
    ConfidenceMetric,
    EvidenceKind,
    LocalAnalysisSource,
    LocalAnalyzerIdentity,
    LocalArtifactPath,
    SourceAnalysisRequest,
    can_transition_stage_status,
    derive_run_status,
)
from .provider import LocalSourceAnalysisProvider
from .runtime import (
    CallbackSourceAnalysisRuntime,
    NullSourceAnalysisRuntime,
    SourceAnalysisCancelledError,
    SourceAnalysisRuntime,
)

__all__ = [
    "BASIS_POINTS",
    "AnalysisCancellation",
    "AnalysisCancellationReason",
    "AnalysisEvidence",
    "AnalysisExecutionMode",
    "AnalysisFailure",
    "AnalysisFailureCode",
    "AnalysisMeasurement",
    "AnalysisModel",
    "AnalysisProgress",
    "AnalysisProgressRegressionError",
    "AnalysisRun",
    "AnalysisRunId",
    "AnalysisRunStatus",
    "AnalysisStage",
    "AnalysisStageKind",
    "AnalysisStagePlan",
    "AnalysisStageProgress",
    "AnalysisStageStatus",
    "CallbackSourceAnalysisRuntime",
    "ConfidenceAggregate",
    "ConfidenceAggregationError",
    "ConfidenceAssessment",
    "ConfidenceMetric",
    "EvidenceKind",
    "LocalAnalysisSource",
    "LocalAnalyzerIdentity",
    "LocalArtifactPath",
    "LocalSourceAnalysisProvider",
    "NullSourceAnalysisRuntime",
    "SourceAnalysisCancelledError",
    "SourceAnalysisRequest",
    "SourceAnalysisRuntime",
    "aggregate_confidence",
    "aggregate_progress",
    "can_transition_stage_status",
    "derive_run_status",
]
