"""Immutable artifact records, provenance, and deterministic cache material."""

from __future__ import annotations

import hashlib
import json
from enum import StrEnum
from pathlib import PurePosixPath, PureWindowsPath
from typing import Self

from pydantic import Field, JsonValue, field_validator, model_validator

from .base import DomainModel, UtcDatetime, utc_now
from .identifiers import ArtifactId, LocalizationId, ProjectId, UtteranceId
from .time import RationalTime
from .types import MimeType, NonEmptyStr, SemanticVersion, Sha256, require_unique


class ArtifactType(StrEnum):
    SOURCE_METADATA = "source_metadata"
    CONFORM_MAP = "conform_map"
    PROXY_VIDEO = "proxy_video"
    THUMBNAIL = "thumbnail"
    WAVEFORM = "waveform"
    AUDIO_STEM = "audio_stem"
    TRANSCRIPT = "transcript"
    TRANSLATION = "translation"
    VOICE_TAKE = "voice_take"
    TIMING = "timing"
    SUBTITLE = "subtitle"
    LIPSYNC_VIDEO = "lipsync_video"
    AUDIO_MIX = "audio_mix"
    QC_REPORT = "qc_report"
    RENDER = "render"
    EXPORT_VALIDATION = "export_validation"


class ArtifactStatus(StrEnum):
    STAGED = "staged"
    VERIFIED = "verified"
    PUBLISHED = "published"
    TRASHED = "trashed"


class ReproducibilityLevel(StrEnum):
    EXACT = "exact"
    BEST_EFFORT = "best_effort"
    NON_REPRODUCIBLE = "non_reproducible"


class ArtifactMediaMetadata(DomainModel):
    mime_type: MimeType | None = None
    duration: RationalTime | None = None
    sample_rate: int | None = Field(default=None, gt=0, le=768_000)
    channels: int | None = Field(default=None, gt=0, le=64)
    width: int | None = Field(default=None, gt=0, le=65_535)
    height: int | None = Field(default=None, gt=0, le=65_535)

    @model_validator(mode="after")
    def _validate_metadata(self) -> Self:
        if self.duration is not None and self.duration.ticks < 0:
            raise ValueError("artifact duration cannot be negative")
        if (self.width is None) != (self.height is None):
            raise ValueError("artifact video dimensions require both width and height")
        return self


class ArtifactProvenance(DomainModel):
    """Execution facts required to reproduce or explain generated bytes."""

    source_artifact_hashes: tuple[Sha256, ...] = ()
    engine_id: NonEmptyStr | None = None
    engine_version: SemanticVersion | None = None
    engine_abi: NonEmptyStr | None = None
    model_id: NonEmptyStr | None = None
    model_version: NonEmptyStr | None = None
    weight_sha256: Sha256 | None = None
    code_version: NonEmptyStr
    provider_id: NonEmptyStr | None = None
    provider_request_id: NonEmptyStr | None = None
    prompt_version: NonEmptyStr | None = None
    normalized_settings: dict[str, JsonValue] = Field(default_factory=dict)
    seed: int | None = None
    hardware: NonEmptyStr | None = None
    precision: NonEmptyStr | None = None
    quality_metrics: dict[str, float | int | str | bool] = Field(default_factory=dict)
    reproducibility: ReproducibilityLevel

    @model_validator(mode="after")
    def _validate_provenance(self) -> Self:
        require_unique(self.source_artifact_hashes, field_name="source_artifact_hashes")
        if self.engine_version is not None and self.engine_id is None:
            raise ValueError("engine version requires an engine identifier")
        if self.engine_abi is not None and self.engine_id is None:
            raise ValueError("engine ABI requires an engine identifier")
        if self.model_version is not None and self.model_id is None:
            raise ValueError("model version requires a model identifier")
        if self.weight_sha256 is not None and self.model_id is None:
            raise ValueError("weight hash requires a model identifier")
        if self.provider_request_id is not None and self.provider_id is None:
            raise ValueError("provider request identifier requires a provider identifier")
        if (
            self.reproducibility is ReproducibilityLevel.EXACT
            and self.engine_id is not None
            and (self.engine_version is None or self.engine_abi is None)
        ):
            raise ValueError("exact engine output requires engine version and ABI")
        return self

    def cache_key(self) -> Sha256:
        """Hash only normalized inputs and implementation decisions, never timestamps/hardware."""

        material = {
            "source_artifact_hashes": self.source_artifact_hashes,
            "engine_id": self.engine_id,
            "engine_version": self.engine_version,
            "engine_abi": self.engine_abi,
            "model_id": self.model_id,
            "model_version": self.model_version,
            "weight_sha256": self.weight_sha256,
            "code_version": self.code_version,
            "provider_id": self.provider_id,
            "prompt_version": self.prompt_version,
            "normalized_settings": self.normalized_settings,
            "seed": self.seed,
            "precision": self.precision,
        }
        encoded = json.dumps(
            material,
            ensure_ascii=False,
            allow_nan=False,
            separators=(",", ":"),
            sort_keys=True,
        ).encode("utf-8")
        return hashlib.sha256(encoded).hexdigest()


class Artifact(DomainModel):
    """Content-addressed output; publication is represented explicitly in lifecycle fields."""

    artifact_id: ArtifactId
    project_id: ProjectId
    localization_id: LocalizationId | None = None
    utterance_id: UtteranceId | None = None
    artifact_type: ArtifactType
    relative_path: str = Field(min_length=1, max_length=1_024)
    sha256: Sha256
    byte_length: int = Field(ge=0)
    source_artifact_ids: tuple[ArtifactId, ...] = ()
    status: ArtifactStatus = ArtifactStatus.STAGED
    media: ArtifactMediaMetadata | None = None
    provenance: ArtifactProvenance
    created_at: UtcDatetime = Field(default_factory=utc_now)
    verified_at: UtcDatetime | None = None
    published_at: UtcDatetime | None = None

    @field_validator("relative_path")
    @classmethod
    def _safe_relative_path(cls, value: str) -> str:
        if "\\" in value:
            raise ValueError("artifact path must use POSIX separators")
        posix = PurePosixPath(value)
        windows = PureWindowsPath(value)
        if posix.is_absolute() or windows.is_absolute() or windows.drive:
            raise ValueError("artifact path must be project-relative")
        if any(part in {"", ".", ".."} for part in posix.parts):
            raise ValueError("artifact path cannot contain empty, dot, or parent segments")
        normalized = posix.as_posix()
        if normalized != value:
            raise ValueError("artifact path must already be normalized")
        return value

    @model_validator(mode="after")
    def _validate_lifecycle(self) -> Self:
        require_unique(self.source_artifact_ids, field_name="source_artifact_ids")
        if self.artifact_id in self.source_artifact_ids:
            raise ValueError("artifact cannot depend on itself")
        if self.verified_at is not None and self.verified_at < self.created_at:
            raise ValueError("artifact verification cannot precede creation")
        if self.published_at is not None:
            if self.verified_at is None:
                raise ValueError("published artifact requires verification before publication")
            if self.published_at < self.verified_at:
                raise ValueError("artifact publication cannot precede verification")
        if self.status is ArtifactStatus.STAGED:
            if self.verified_at is not None or self.published_at is not None:
                raise ValueError("staged artifact cannot have verification/publication timestamps")
        elif self.status is ArtifactStatus.VERIFIED:
            if self.verified_at is None or self.published_at is not None:
                raise ValueError("verified artifact requires only a verification timestamp")
        elif self.status is ArtifactStatus.PUBLISHED and (
            self.verified_at is None or self.published_at is None
        ):
            raise ValueError("published artifact requires verification and publication timestamps")
        return self


__all__ = [
    "Artifact",
    "ArtifactMediaMetadata",
    "ArtifactProvenance",
    "ArtifactStatus",
    "ArtifactType",
    "ReproducibilityLevel",
]
